from time import time

pairs_to_show = {
                'BTC': [{'platform_link': 'https://www.xt.com/tradePro/btc_usdt',
                         'platform': 'XT',
                         'method_args': {'pair': 'btc_usdt',
                                         'period_s': '1m'},
                         'title': 'BTC short __ btc_usdt __ 4 HOURS',
                         'reverse': True},
                         {'platform_link': 'https://www.xt.com/tradePro/btc_usdt',
                          'platform': 'XT',
                          'method_args': {'pair': 'btc_usdt',
                                          'period_s': '1d'},
                          'title': 'BTC long __ btc_usdt __ 3 MONTHS',
                         'reverse': True}],
                'XCH': [
                       {'platform_link': 'https://www.xt.com/tradePro/xch_usdt',
                        'platform': 'XT',
                        'method_args': {'pair': 'xch_usdt',
                                        'period_s': '1m'},
                        'title': 'XCH short __ xch_usdt __ 4 HOURS',
                         'reverse': True},
                        {'platform_link': 'https://www.xt.com/tradePro/xch_usdt',
                         'platform': 'XT',
                         'method_args': {'pair': 'xch_usdt',
                                         'period_s': '1d'},
                         'title': 'XCH long __ xch_usdt __ 3 MONTHS',
                         'reverse': True}
                ],
                'SIT': [
                       {'platform_link': 'https://trade.citex.co.kr/trade/SIT_USDT',
                        'platform': 'CITEX',
                        'method_args': {'pair': 'sit_usdt',
                                        'period_m': 3, # 1 does not work as of 21 Mar 2022
                                        'size': 120},
                        'title': 'SIT short __ sit_usdt __ 6 HOURS',
                         'reverse': True},
                        {'platform_link': 'https://trade.citex.co.kr/trade/SIT_USDT',
                         'platform': 'CITEX',
                         'method_args': {'pair': 'sit_usdt',
                                         'period_m': 1440,
                                         'size': 300},
                         'title': 'SIT long __ sit_usdt __ 10 MONTHS',
                         'reverse': True},
                ],
                'XCC': [
                    {'platform_link': 'https://www.lbank.info/exchange/xcc/usdt',
                     'platform': 'LBANK',
                     'method_args': {'symbol': 'xcc_usdt',
                                     'size': 360,
                                     'API_type': 'minute1',
                                     'timestamp': (lambda : int(time()) - 360*60)},
                     'title': 'XCC short __ xcc_usdt __ 6 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://www.lbank.info/exchange/xcc/usdt',
                     'platform': 'LBANK',
                     'method_args': {'symbol': 'xcc_usdt',
                                     'size': 300,
                                     'API_type': 'day1',
                                     'timestamp': (lambda : int(time()) - 300*24*60*60)},
                     'title': 'XCC long __ xcc_usdt __ 10 MONTHS',
                     'reverse': False},
                ],
                'HDD': [
                    {'platform_link': 'https://vayamos.cc/spot/HDD_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'HDD/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'HDD short __ hdd_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/HDD_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'HDD/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'HDD long __ hdd_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'XCD': [
                    {'platform_link': 'https://vayamos.cc/spot/XCD_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XCD/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XCD short __ XCD_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/XCD_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XCD/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XCD long __ XCD_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'PROFIT': [
                    {'platform_link': 'https://vayamos.cc/spot/PROFIT_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'PROFIT/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'PROFIT short __ PROFIT_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/PROFIT_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'PROFIT/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'PROFIT long __ PROFIT_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'BPX': [
                    {'platform_link': 'https://vayamos.cc/spot/BPX_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'BPX/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'BPX short __ BPX_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/BPX_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'BPX/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'BPX long __ BPX_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'TAD': [
                    {'platform_link': 'https://vayamos.cc/spot/TAD_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'TAD/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'TAD short __ TAD_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/TAD_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'TAD/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'TAD long __ TAD_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'XBTC': [
                    {'platform_link': 'https://vayamos.cc/spot/XBTC_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XBTC/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XBTC short __ XBTC_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/XBTC_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XBTC/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XBTC long __ XBTC_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'CAC': [
                    {'platform_link': 'https://vayamos.cc/spot/CAC_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'CAC/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'CAC short __ CAC_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/CAC_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'CAC/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'CAC long __ CAC_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'XPT': [
                    {'platform_link': 'https://vayamos.cc/spot/XPT_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XPT/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XPT short __ XPT_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/XPT_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XPT/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XPT long __ XPT_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'XSHIB': [
                    {'platform_link': 'https://vayamos.cc/spot/XSHIB_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XSHIB/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XSHIB short __ XSHIB_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/XSHIB_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XSHIB/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XSHIB long __ XSHIB_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'ECO': [
                    {'platform_link': 'https://vayamos.cc/spot/ECO_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'ECO/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'ECO short __ ECO_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/ECO_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'ECO/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'ECO long __ ECO_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'XFX': [
                    {'platform_link': 'https://vayamos.cc/spot/XFX_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XFX/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XFX short __ XFX_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/XFX_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XFX/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XFX long __ XFX_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'GDOG': [
                    {'platform_link': 'https://vayamos.cc/spot/GDOG_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'GDOG/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'GDOG short __ GDOG_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/GDOG_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'GDOG/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'GDOG long __ GDOG_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'XMZ': [
                    {'platform_link': 'https://vayamos.cc/spot/XMZ_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XMZ/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XMZ short __ XMZ_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/XMZ_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'XMZ/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'XMZ long __ XMZ_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'STAI': [
                    {'platform_link': 'https://vayamos.cc/spot/STAI_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'STAI/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'STAI short __ STAI_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/STAI_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'STAI/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'STAI long __ STAI_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'GL': [
                    {'platform_link': 'https://vayamos.cc/spot/GL_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'GL/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'GL short __ GL_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/GL_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'GL/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'GL long __ GL_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'LLC': [
                    {'platform_link': 'https://vayamos.cc/spot/LLC_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'LLC/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'LLC short __ LLC_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/LLC_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'LLC/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'LLC long __ LLC_usdt __ 6 MONTHS',
                     'reverse': False},
                ],
                'STOR': [
                    {'platform_link': 'https://vayamos.cc/spot/STOR_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'STOR/USDT',
                                     'res': '1',
                                     'from_tmstmp': (lambda : int(time()) - 24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'STOR short __ STOR_usdt __ 24 HOURS',
                     'reverse': False},
                    {'platform_link': 'https://vayamos.cc/spot/STOR_USDT',
                     'platform': 'VAYAMOS',
                     'method_args': {'pair': 'STOR/USDT',
                                     'res': '1D',
                                     'from_tmstmp': (lambda : int(time()) - 6*30*24*60*60),
                                     'to_tmstmp': (lambda : int(time()))},
                     'title': 'STOR long __ STOR_usdt __ 6 MONTHS',
                     'reverse': False},
                ]
}