pairs_to_show = {'BTC': [{'platform_link': 'https://www.xt.com/tradePro/btc_usdt',
                         'platform': 'XT',
                         'method_args': {'pair': 'btc_usdt',
                                         'period_s': 3600},
                         'title': 'BTC short __ btc_usdt __ 4 DAYS'},
                         {'platform_link': 'https://www.xt.com/tradePro/btc_usdt',
                          'platform': 'XT',
                          'method_args': {'pair': 'btc_usdt',
                                          'period_s': 86400},
                          'title': 'BTC long __ btc_usdt __ 100 DAYS'}],
                 'HDD': [{'platform_link': 'https://www.xt.com/tradePro/hdd_usdt',
                         'platform': 'XT',
                         'method_args': {'pair': 'hdd_usdt',
                                         'period_s': 3600},
                         'title': 'HDD short __ hdd_usdt __ 4 DAYS'},
                         {'platform_link': 'https://www.xt.com/tradePro/hdd_usdt',
                          'platform': 'XT',
                          'method_args': {'pair': 'hdd_usdt',
                                          'period_s': 86400},
                          'title': 'HDD long __ hdd_usdt __ 100 DAYS'},
                         ],
                 'SPARE': [{'platform_link': 'https://www.xt.com/tradePro/spare_usdt',
                         'platform': 'XT',
                         'method_args': {'pair': 'spare_usdt',
                                         'period_s': 3600},
                         'title': 'SPARE short __ spare_usdt __ 4 DAYS'},
                         {'platform_link': 'https://www.xt.com/tradePro/spare_usdt',
                          'platform': 'XT',
                          'method_args': {'pair': 'spare_usdt',
                                          'period_s': 86400},
                          'title': 'SPARE long __ spare_usdt __ 100 DAYS'}],
                 'XCH': [{'platform_link': 'https://www.xt.com/tradePro/xch_usdt',
                         'platform': 'XT',
                         'method_args': {'pair': 'xch_usdt',
                                         'period_s': 3600},
                         'title': 'XCH short __ xch_usdt __ 4 DAYS'},
                         {'platform_link': 'https://www.xt.com/tradePro/xch_usdt',
                          'platform': 'XT',
                          'method_args': {'pair': 'xch_usdt',
                                          'period_s': 86400},
                          'title': 'XCH long __ xch_usdt __ 100 DAYS'}]}